### ISSUE TITLE
Use consolidated-events

### ISSUE THREAD

**Issue by jamesplease** [rehooks/window-size#2]
This library could benefit from using [consolidated-events](https://github.com/lencioni/consolidated-events) to limit the number of handlers being registered. The downside, of course, is that it adds a dependency.

I'd be happy to make a PR if you're :+1: to the idea. No worries if not, though.

Thanks for reading!

**Comment by jamiebuilds** [comment]
I think it's probably fine, if people actually end up using this and have a perf problem I'll do it
